### ISSUE TITLE
Since 6.2.5, missing required field id when indexing an empty array

### ISSUE THREAD

**Issue by ambroisemaupate** [solariumphp/solarium#1023]
**Solarium version(s) affected**: 6.2.5
**Solr version**: 8.11

**Description**  

Solr complains about missing `id` field but this field is present in every Document. This issue started to occur after upgrading to solarium 6.2.5. This is issue does not occur on 6.2.4:

```
Solr HTTP error: OK (400)                                          
  {                                                                  
    "responseHeader":{                                               
      "status":400,                                                  
      "QTime":1},                                                    
    "error":{                                                        
      "metadata":[                                                   
        "error-class","org.apache.solr.common.SolrException",        
        "root-error-class","org.apache.solr.common.SolrException"],  
      "msg":"[doc=null] missing required field: id",                 
      "code":400}}      
```

**How to reproduce**  

A simple test to reproduce is to try to index an empty array field:
```php
// get an update query instance
$update = $client->createUpdate();
$doc1 = $update->createDocument();
$doc1->id = 123;
$doc1->name = 'testdoc';
$doc1->price = 364;
$doc1->setField('collection_txt', [
                    0 => 'line 1',
                    1 => 'line 2',
                    2 => 'line 3',
]);
$doc1->setField('tags_txt_en', []);
$update->addDocument($doc1);
$update->addCommit();
$result = $client->update($update);
```

---

Here a dump of an update Query containing 2 documents to add to Solr, these 2 docs contain `id` field.
```
Solarium\QueryType\Update\Query\Query^ {#13746
  #options: array:4 [
    "handler" => "update"
    "resultclass" => "Solarium\QueryType\Update\Result"
    "documentclass" => "Solarium\QueryType\Update\Query\Document"
    "omitheader" => false
  ]
  #helper: null
  #params: []
  -localParameters: null
  #commandTypes: array:6 [
    "add" => "Solarium\QueryType\Update\Query\Command\Add"
    "commit" => "Solarium\QueryType\Update\Query\Command\Commit"
    "delete" => "Solarium\QueryType\Update\Query\Command\Delete"
    "optimize" => "Solarium\QueryType\Update\Query\Command\Optimize"
    "rawxml" => "Solarium\QueryType\Update\Query\Command\RawXml"
    "rollback" => "Solarium\QueryType\Update\Query\Command\Rollback"
  ]
  #commands: array:1 [
    0 => Solarium\QueryType\Update\Query\Command\Add^ {#449
      #options: []
      #documents: array:2 [
        0 => Solarium\QueryType\Update\Query\Document^ {#473
          #fields: array:19 [
            "id" => "62d911ce3144d1.02715591"
            "document_type_s" => "DocumentTranslation"
            "document_translation_id_i" => 1
            "document_id_i" => 1
            "created_at_dt" => "2021-09-17T10:19:59Z"
            "updated_at_dt" => "2022-06-23T14:00:35Z"
            "copyright_valid_since_dt" => "2022-06-15T19:00:00Z"
            "copyright_valid_until_dt" => "9999-12-31T22:59:59Z"
            "filename_s" => "2v3wckaloli_photo_1631298338669_7921e0c25422_crop_entropy_cs_srgb_fm_jpg_ixid_mnwyndmyodj8mhwxfhjhbmrvbxx8fhx8fhx8fde2mze4nzm5otk_ixlib_rb_1.2.1_q_85.jpg"
            "mime_type_s" => "image/jpeg"
            "locale_s" => "en"
            "title" => ""
            "title_txt_en" => ""
            "description_txt_en" => "city skyline during night time"
            "copyright_txt_en" => "Jeanson Wong, Unsplash"
            "tags_txt" => []
            "tags_txt_en" => ""
            "collection_txt" => array:3 [
              0 => ""
              1 => "city skyline during night time"
              2 => "Jeanson Wong, Unsplash"
            ]
            "collection_txt_en" => """
              \n
              city skyline during night time\n
              Jeanson Wong, Unsplash
              """
          ]
          #boost: null
          #modifiers: []
          #key: "id"
          #fieldBoosts: []
          #version: null
        }
        1 => Solarium\QueryType\Update\Query\Document^ {#457
          #fields: array:19 [
            "id" => "62d911ce3801f8.35434180"
            "document_type_s" => "DocumentTranslation"
            "document_translation_id_i" => 2
            "document_id_i" => 1
            "created_at_dt" => "2021-09-17T10:19:59Z"
            "updated_at_dt" => "2022-06-23T14:00:35Z"
            "copyright_valid_since_dt" => "2022-06-15T19:00:00Z"
            "copyright_valid_until_dt" => "9999-12-31T22:59:59Z"
            "filename_s" => "2v3wckaloli_photo_1631298338669_7921e0c25422_crop_entropy_cs_srgb_fm_jpg_ixid_mnwyndmyodj8mhwxfhjhbmrvbxx8fhx8fhx8fde2mze4nzm5otk_ixlib_rb_1.2.1_q_85.jpg"
            "mime_type_s" => "image/jpeg"
            "locale_s" => "fr"
            "title" => ""
            "title_txt_fr" => ""
            "description_txt_fr" => "city skyline during night time"
            "copyright_txt_fr" => "Jeanson Wong, Unsplash"
            "tags_txt" => []
            "tags_txt_fr" => ""
            "collection_txt" => array:3 [
              0 => ""
              1 => "city skyline during night time"
              2 => "Jeanson Wong, Unsplash"
            ]
            "collection_txt_fr" => """
              \n
              city skyline during night time\n
              Jeanson Wong, Unsplash
              """
          ]
          #boost: null
          #modifiers: []
          #key: "id"
          #fieldBoosts: []
          #version: null
        }
      ]
    }
  ]
}
```

Solr returns error at Query update: missing required field id

```
  Solr HTTP error: OK (400)                                          
  {                                                                  
    "responseHeader":{                                               
      "status":400,                                                  
      "QTime":1},                                                    
    "error":{                                                        
      "metadata":[                                                   
        "error-class","org.apache.solr.common.SolrException",        
        "root-error-class","org.apache.solr.common.SolrException"],  
      "msg":"[doc=null] missing required field: id",                 
      "code":400}} 
```

**Possible Solution**  
Fallback to v6.2.4 fixes this problem

**Comment by thomascorthals** [comment]
@leuchtdiode This is the same you're having.

**Comment by leuchtdiode** [comment]
Yep, exactly the same problem.

**Comment by ambroisemaupate** [comment]
I think this is due to `setField` or `addField` with an `array` value. It considers that this is a nested document, but it's just a multi-valued field :

```
"collection_txt" => array:3 [
              0 => ""
              1 => "city skyline during night time"
              2 => "Jeanson Wong, Unsplash"
]
```

**Comment by thomascorthals** [comment]
It's `buildFieldsXml` in the RequestBuilder.

**Comment by ambroisemaupate** [comment]
RequestBuilder.php, Line 272 

Does this fix the problem for you @leuchtdiode? 

```diff
- if (is_numeric(array_key_first($value)) {
+ if (is_numeric(array_key_first($value)) ||  empty($value)) {
```

**Comment by thomascorthals** [comment]
I think this fixes the problem.

```diff
diff --git a/src/QueryType/Update/RequestBuilder.php b/src/QueryType/Update/RequestBuilder.php
index d1fcd47ddd0..f8c273187de 100644
--- a/src/QueryType/Update/RequestBuilder.php
+++ b/src/QueryType/Update/RequestBuilder.php
@@ -268,7 +268,7 @@ class RequestBuilder extends BaseRequestBuilder
             $value = null;
         }

-        if (\is_array($value)) {
+        if (\is_array($value) && !empty($value)) {
             if (is_numeric(array_key_first($value))) {
                 $nestedXml = '';

@@ -312,7 +312,7 @@ class RequestBuilder extends BaseRequestBuilder
                 }
                 $xml .= '</doc>';
             }
-        } else {
+        } elseif (\is_scalar($value)) {
             $xml .= $this->buildFieldXml($key, $boost, $value, $modifier);
         }
```

I'll have to update some tests before I can open a PR to prevent regressions though.

**Comment by thomascorthals** [comment]
> I think this fixes the problem.

Almost. `is_scalar` returns `false` for `DateTime` objects, obviously.

**Comment by leuchtdiode** [comment]
I broke my tests due to another change. I will give it a try as soon as I'm ready

**Comment by leuchtdiode** [comment]
Unfortunately all of my tests are breaking now with `Document is missing mandatory uniqueKey field: id`

**Comment by thomascorthals** [comment]
https://github.com/thomascorthals/solarium/commit/06612832be4cb4f28728d50f7364b01d89ba55ae seems to fix it, waiting on the test matrix to complete before I open a PR.

**Comment by ambroisemaupate** [comment]
@thomascorthals I think the issue is still occuring if your app index a non-numeric key-valued array:

```php
$update = $client->createUpdate();
$doc1 = $update->createDocument();
$doc1->id = 123;
$doc1->name = 'testdoc';
$doc1->setField('collection_txt', [
    'line-1' => 'line 1',
    'line-2' => 'line 2',
    2 => 'line 3',
]);
$update->addDocument($doc1);
$update->addCommit();
$result = $client->update($update);
```

**Comment by thomascorthals** [comment]
@ambroisemaupate The distinction between multi values and a child document is made by detecting if the first index is numeric or not. A sort of poor man's [array_is_list](https://www.php.net/manual/en/function.array-is-list) that's already lenient about non-consecutive indices.

In your case, you can get the desired behaviour with:
```php
$doc1->setField('collection_txt', array_keys([
    'line-1' => 'line 1',
    'line-2' => 'line 2',
    2 => 'line 3',
]));
```

**Comment by thomascorthals** [comment]
We could detect if any key in the array is numeric, but that would impose a performance hit for an edge case where we can't be sure if the user has a mixed-key multi value or an erroneous field name in a nested child document. If the update fails, the user is forced to find out why. Which I consider preferable to silently picking one of two possibilities without the user realising it might be the wrong one in the case at hand.

We could be more explicit about numeric indices vs. string keys in the docs.

To avoid all ambiguity, we would have to allow a `Document` instance to be set as a field value. That thought has crossed my mind before, but we would still have to maintain the current functionality for at least the next major release as well. No longer treating string-keyed arrays as child document would be quite the BC break to fix for some users.

**Comment by thomascorthals** [comment]
> We could be more explicit about numeric indices vs. string keys in the docs.

I've updated the PR to mention this in the docs.

**Comment by thomascorthals** [comment]
@ambroisemaupate @leuchtdiode The fix was released as [Solarium 6.2.6](https://github.com/solariumphp/solarium/releases/tag/6.2.6).

**Comment by leuchtdiode** [comment]
Thx. I will give it a try later.

**Comment by leuchtdiode** [comment]
Looks good now, no errors from Solr, thank you.

**Comment by douglasmiguel** [comment]
Hi, I'm using the `"solarium/solarium": "^6.3",` and I'm still having issues to index array keys.

I want to index an object that looks like this:

```
Solarium\QueryType\Update\Query\Document^ {#894
  #fields: array:9 [
    "reporting_partition_id" => 111
    "report_date" => "2021-05-15"
    "partner_account_ref" => "P12"
    "campaign" => "mobile"
    "medium" => "link"
    "page_view_count" => 1
    "bookings" => array:1 [
      0 => array:7 [
        "itinerary_item_id" => 12
        "itinerary_item_status" => 1
        "value_original_usd" => "18.5"
        "value_actual_usd" => "18.5"
        "traveller_count" => 1
        "commission_original_usd" => "1.48"
        "device_type" => 3
      ]
    ]
    "product_code" => "123"
    "destination_id" => 12
  ]
  #boost: null
  #modifiers: []
  #key: null
  #fieldBoosts: []
  #version: null
  #helper: null
}
```

But I keep getting a error about the `itinerary_item_id` field being not defined.

```
Solr HTTP error: OK (400)
{
  "responseHeader":{
    "status":400,
    "QTime":4
  },
  "error":{
    "metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],
    "msg":"ERROR: [doc=b7b37e15-ce68-4e56-9651-70ec944530e2/bookings#] unknown field 'itinerary_item_id'",
    "code":400
  }
}
```

Can you please help me?

**Comment by thomascorthals** [comment]
@douglasmiguel Does your schema conform to[these points from the [ref guide](https://solr.apache.org/guide/solr/latest/indexing-guide/indexing-nested-documents.html#schema-configuration)?

> Finally, understand that nested child documents are very much documents in their own right even if certain nested documents hold different information from the parent or other child documents, therefore:
> * All field names in the schema can only be configured in one — different types of child documents can not have the same field name configured in different ways.
> * It may be infeasible to use `required` for any field names that aren’t required for all types of documents.
> * Even child documents need a _globally_ unique `id`.

It looks like you don't have a matching field (or dynamic field) definition for `itinerary_item_id`. Or a globally unique `id` for that matter.

**Comment by douglasmiguel** [comment]
Hi @thomascorthals, first of all, thank you for the quick reply.

I'm also trying to use the example from the example project: `https://github.com/solariumphp/solarium` and I'm getting errors:

```
$update = $this->client->createUpdate();
$doc1 = $update->createDocument();
$doc1->id = 123;
$doc1->name = 'testdoc-1';
$doc1->childdocs = array(
    array(
        'id' => 1230,
        'name' => 'childdoc-1-1',
        'price' => 465,
    ),
    array(
        'id' => 1231,
        'name' => 'childdoc-1-2',
        'price' => 545,
    ),
);
$update->addDocument($doc1);
$update->addCommit();
$result = $this->client->update($update);
```

```
  Solr HTTP error: OK (400)
{
  "responseHeader":{
    "status":400,
    "QTime":0
  },
  "error":{
    "metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],
    "msg":"ERROR: [doc=1230] unknown field 'price'",
    "code":400
  }
}
```

**Comment by douglasmiguel** [comment]
As for the other points, I'll make sure to follow them. But at the moment, I have an empty Solr Core, and I'm trying to insert one document.

**Comment by thomascorthals** [comment]
> I'm also trying to use the example from the example project: `https://github.com/solariumphp/solarium` and I'm getting errors:

Did you run this against Solr's techproducts example, or your own empty core? If you start from `bin/solr start -e techproducts` you should have the price field available. Check what it shows at http://localhost:8983/solr/#/techproducts/schema?field=price (adjust host if necessary).

**Comment by douglasmiguel** [comment]
@th

> > I'm also trying to use the example from the example project: `https://github.com/solariumphp/solarium` and I'm getting errors:
> 
> Did you run this against Solr's techproducts example or your own empty core? If you start from `bin/solr start -e techproducts` you should have the price field available. Check what it shows at http://localhost:8983/solr/#/techproducts/schema?field=price (adjust host if necessary).

I'm new to Solr, so that might be the problem, I was expecting the schema to be flexible and insert the new fields since it worked with simple objects.

I need to define the Schema before for nested fields, gotcha - I will learn how to do it, thank you.

**Comment by douglasmiguel** [comment]
Yes, by adding the `price` field to my schema, it now works!

Thank you so much, I just need to create the schema accordingly with my database now, and I should be fine.

**Comment by thomascorthals** [comment]
Solr has a [Schemaless Mode](https://solr.apache.org/guide/solr/latest/indexing-guide/schemaless-mode.html) that guesses field types from data you insert. Can be used as a starting point for your own schema but I would look at the results very carefully.

**Comment by douglasmiguel** [comment]
Thank you @thomascorthals, I do have a very well-defined schema, it will be easier to create the missing fields. :)
